version: '3.8'
services:
  # --- BD CLOUD (Puerto 5440) ---
  postgres-cloud:
    image: postgres:15
    container_name: postgres-cloud
    environment:
      - POSTGRES_DB=Db_Cloud
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=clave
    ports:
      - "5440:5432"  # Mapeamos el puerto interno 5432 al 5440 para tu PC
    volumes:
      - ./sql/cloud_init.sql:/docker-entrypoint-initdb.d/init.sql

  # --- BD LEGACY (Puerto 5441) ---
  postgres-legacy:
    image: postgres:15
    container_name: postgres-legacy
    environment:
      - POSTGRES_DB=Db_OnPremise
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=clave
    ports:
      - "5441:5432"  # Mapeamos el puerto interno 5432 al 5441 para tu PC
    volumes:
      - ./sql/legacy_init.sql:/docker-entrypoint-initdb.d/init.sql